# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Setup environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build web
    - run: git clone https://github.com/definev/definev.github.io.git
    - run: ls
    - run: cd ./build
    - run: ls
    - run: cd ..
    - run: cp -a .build/web/. .define.github.io/
    - run: cd ./define.github.io
    - run: git add .
    - run: git commit -m "Deploy portfolio"
    - run: git push
    
